#!/usr/bin/env python
# -*- coding: utf-8 -*-
from tori.application import Application
from tori.cli.console import Console
from tori.cli.exception import TerminationSignal

app     = Application('config/app.xml')
console = Console('NEP')

console.load(app);

try:
    console.handle()
except TerminationSignal as e:
    pass